version: "3.8"

services:
  web:
    build: "web"
    restart: "always"
    depends_on:
      - service
    expose:
      - "80"
    ports:
      - "80:80"

  service:
    build: "service"
    restart: "always"
    expose:
      - "3000"
