version: "3.8"

services:
  web:
    build: "web"
    image: "godow/compile-web"
    depends_on:
      - server
    expose:
      - "80"
    ports:
      - "7777:80"

  server:
    build: "server"
    image: "godow/compile-server"
    expose:
      - "3000"
    ports:
      - "3000:3000"
