FROM node:latest
RUN mkdir -p /app/service
COPY . /app/service
WORKDIR /app/service
RUN npm install -g cnpm --registry=https://registry.npmmirror.com/
RUN cnpm config set registry https://registry.npmmirror.com/
RUN cnpm install
EXPOSE 3000
CMD [ "node", "index.js"]
