FROM node:alpine3.16 AS builder
RUN mkdir -p /app/server
COPY . /app/server
WORKDIR /app/server
RUN npm install -g cnpm --registry=https://registry.npmmirror.com/
RUN cnpm config set registry https://registry.npmmirror.com/
RUN cnpm install && cnpm run build

FROM ubuntu:18.04
RUN mkdir -p /app/server
COPY --from=builder /app/server/dist /app/server
COPY install_env.sh /app/server/
WORKDIR /app/server

RUN chmod +x install_env.sh && ./install_env.sh

EXPOSE 3000
CMD [ "nohup", "node", "index.js", "&"]
